server:
  port: 1110

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/word?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: 123abc
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: tech.yuliu.bean

logging:
  level:
    com:
      example:
        mapper: info


wechat:
  appid: wxfd627e375c1cbe4c
  appSecret: f6f8debe7298693093c675af9f176892

alias-mapping:
  category:
    cet4: 英语四级
    cet6: 英语六级
    master: 考研英语
  category-zh:
    '[英语四级]': cet4
    '[英语六级]': cet6
    '[考研英语]': master

word:
  review-multiple: 3
  default-attenuation: 0.155
  min-attenuation: 0.0575
  max-memory: 100
  max-time: 10368000
  memory-threshold: 50
  memory-low-threshold: 25
